---
- name: Create /opt/src
  become: yes
  file: path=/opt/src state=directory recurse=yes

- name: Create lib dir
  become: yes
  file: path={{sbt_lib_path_target}} state=directory recurse=yes

- name: Download and Unpack sbt
  become: yes
  unarchive: src={{sbt_download_url}} dest={{sbt_lib_path_target}} copy=no

- name: Link sbt
  become: yes
  file: state=link src={{sbt_lib_path_target}}/sbt/bin/sbt dest={{sbt_link_target}}